require("core.plugin_config.colorscheme")
require("core.plugin_config.lsp_config")
require("core.plugin_config.neotest")
require("core.plugin_config.neodev")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.which-key")
